[build]
target = "riscv32imac-unknown-none-elf"
rustflags = ["-C", "force-frame-pointers"]

[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip esp32c6"

[unstable]
build-std = ["core"]

[env]
ESP_LOG="INFO"