[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
  "-C", "force-frame-pointers",
]

[unstable]
build-std = ["core"]

[env]
ESP_LOG_LEVEL = "INFO"